"""Schema v4 baseline

Establishes the full LuminaFPM Schema v4 as the initial Alembic revision. Because
the project is converting from ``Base.metadata.create_all`` to managed migrations,
this baseline creates every registered table from the model metadata (core Schema
v4 tables + the still-wired LTI threat-intel tables loaded in env.py).

Subsequent revisions MUST be incremental (autogenerated `op.*` operations), not
metadata create_all.

Operational note: on an existing dev database previously built with create_all,
run `alembic stamp 0001_schema_v4_baseline` instead of upgrade (tables already
exist), or drop & re-create the dev DB. See docs/EXECUTION_LOG.md.

Revision ID: 0001_schema_v4_baseline
Revises:
Create Date: 2026-06-22
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_schema_v4_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # env.py has already imported the model modules, fully populating Base.metadata.
    from models.models import Base

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    from models.models import Base

    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
